---
title: "Day 3 - Conditionals & Loops"
author: "Elise Gonzales"
date: "2022-08-10"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
#include = FALSE makes it so NOTHING from this code chunk will show up on rendered doc.

library(tidyverse)
library(palmerpenguins)
library(starwars)

```

### `if` statements
```{r}
burrito <- 0.7

if (burrito > 2) {
  print("I love burritos!")
}
```

String detect: Does this pattern show up anywhere in this element? T/F
```{r}
my_ships <- c("Millenium Falcon", "X-wing", "Tie-Fighter", "Death Star")

str_detect(my_ships, pattern = "X")

phrase <- "I love burritos"

if (str_detect(phrase, "love")) {
  print("I am a burrito fan.")
}
```

## `if-else` statement

```{r}
pika <- 89.1

if (pika > 60) {
  print("mega pika")
} else {
  print("normal pika")
}
```

## `if-else-if` statement

```{r}
marmot <- 2.8

if (marmot < 0.5) {
  print("this is a small marmot")
} else if (marmot >= 0.5 & marmot < 3) {
  print("this is a medium marmot")
} else {
  print("this is a large marmot")
}
```


```{r}
tatooine_characters <- starwars |> 
  filter(homeworld == "Tatooine") 

#Use %in% operator to check for multiple positive matches.
tatooine_endor_naboo <- starwars |> 
  filter(homeworld %in% c("Tatooine", "Naboo", "Endor"))
# In words: does the value in the homeworld variable for that row exist IN that vector c("Tatooine" "Nab...)?
```

## Calculate mean bill length by species using `group by |> summarize`
```{r}
penguins |> 
  group_by(species, island) |> 
  summarize(mean_bill_length = mean(bill_length_mm, na.rm = TRUE),
            sd_bill_length = sd(bill_length_mm, na.rm = TRUE),
            n=n())  
# n=n() doesnt take na.rm=true into account; so, it counts everything including na 

# summarize takes given function and applies it to group, calculating single function for each group, then returns it in a summary table. 

# you can also use apply() but ^^this is better 
```

Find the mean & standard deviation of character height in Star Wars, grouped by homeworld.
```{r}
starwars |> 
  group_by(homeworld) |> 
  summarize(mean_character_height = mean(height, na.rm = TRUE),
            sd_character_height = sd(height, na.rm = TRUE))

starwars |> 
  group_by(homeworld) |> 
  summarize(max_height = max(height, na.rm = TRUE),
            min_height = min(height, na.rm = TRUE))
```
 
Find the max & min flipper length, and sample size, for each species of penguin
```{r}
penguins |> 
  group_by(species, sex) |> 
  summarize(max_flipper_length = max(flipper_length_mm, na.rm = TRUE),
            min_flipper_length = min(flipper_length_mm, na.rm = TRUE),
            n = n())
```

